service: serverless2
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: '20201221'

functions:
  users:
    handler: api/user/handler.handler
    events:
      - http:
          path: '/api/user'
          method: any
